### PR TITLE
Update default tomox datadir

### LINKED ISSUE #279: TomoX Default datadir
currently, the default tomox data dir is ${HOME}/.tomo
we should move it to ${DEFAULT_TOMODATADIR}/tomox

### PR DESCRIPTION
**Pull request by thanhnguyennguyen**
TomoX default datadir
- Top priority: $DATADIR/tomox
- Second priority: $HOME_DIR/.tomo

resolve https://github.com/tomochain/tomochain/issues/279

### CODE REVIEW

**Comment by thanhson1085** [comment]
Moving from v2.2.1 to v2.2.2, If running node with docker, the tomox data will be removed if we remove the container. So we need to move it to the right location before removing the container.

The right location is `TOMOCHAIN_DATADIR/tomox`

This guide is for who uses `tmn`

**Step 1:** Find the container id

Try `docker ps` and look up by your eye.
If `tmn` you can find cointainer id by command: `container_id=$(docker ps -q -f "name=tomochain")`

**Step 2:** Move tomox to the right location
```
docker exec -it $cointainer_id cp -R /root/.tomo /tomochain/data/tomox
```
**Step 3:** Checking the backup
Now, we need to make sure the `tomox` data locates at the right directory.

```
docker exec -it $cointainer_id ls data/tomox/
```
Checking the output, it should be:
```
000031.ldb       000042.ldb       000053.ldb       000064.ldb
000032.ldb       000043.ldb       000054.ldb       000065.ldb
000033.ldb       000044.ldb       000055.ldb       000066.log
000034.ldb       000045.ldb       000056.ldb       000067.ldb
000035.ldb       000046.ldb       000057.ldb       CURRENT
000036.ldb       000047.ldb       000058.ldb       LOCK
000037.ldb       000048.ldb       000059.ldb       LOG
000038.ldb       000049.ldb       000060.ldb       MANIFEST-000000
000039.ldb       000050.ldb       000061.ldb       history
000040.ldb       000051.ldb       000062.ldb
000041.ldb       000052.ldb       000063.ldb
```

It should be the same as the output:
```
docker exec -it $cointainer_id ls /root/.tomo
```

**Step 4:** ready for updating
```
tmn update
```

**Review by thanhson1085 — APPROVED** [review]

**Comment by thanhson1085** [comment]
With the nodes use **CTM tool** (https://github.com/tomochain/create-tomochain-masternode), the steps is similar as the above steps (`tmn`).

**Step 1:** Find the container id
Try `docker ps` and look up by your eyes. I depends on the name you set when you created the node.

**Step 2:** Move tomox to the right location
```
docker exec -it YOUR_CONAINER_ID cp -R /root/.tomo /tomochain/data/tomox
```

**Step 3:** Checking the backup
Now, we need to make sure the tomox data locates at the right directory.
```
docker exec -it YOUR_CONAINER_ID ls data/tomox/
```
Checking the output, it should be:
```
000031.ldb       000042.ldb       000053.ldb       000064.ldb
000032.ldb       000043.ldb       000054.ldb       000065.ldb
000033.ldb       000044.ldb       000055.ldb       000066.log
000034.ldb       000045.ldb       000056.ldb       000067.ldb
000035.ldb       000046.ldb       000057.ldb       CURRENT
000036.ldb       000047.ldb       000058.ldb       LOCK
000037.ldb       000048.ldb       000059.ldb       LOG
000038.ldb       000049.ldb       000060.ldb       MANIFEST-000000
000039.ldb       000050.ldb       000061.ldb       history
000040.ldb       000051.ldb       000062.ldb
000041.ldb       000052.ldb       000063.ldb
```
It should be the same as the output:
```
docker exec -it $cointainer_id ls /root/.tomo
```
**Step 4:** ready for updating
```
docker-compose pull
docker-compose up -d
```

**Comment by HorizenCommunityCouncil** [comment]
Using cp while the node is running will corrupt the ldb files for tomox if they are being written to at the time they are copied. cp in Linux does not check if the files are being used by another process. This turns the upgrade process into a lottery, if you are lucky enough to copy the file while it isn't being written to, the upgrade will work, if you are unlucky, you will get a corrupted ldb file and the blockchain will be rest by ~1M blocks.

**Comment by PeaStew** [comment]
Using cp while the node is running will corrupt the ldb files for tomox if they are being written to at the time they are copied. cp in Linux does not check if the files are being used by another process. This turns the upgrade process into a lottery, if you are lucky enough to copy the file while it isn't being written to, the upgrade will work, if you are unlucky, you will get a corrupted ldb file and the blockchain will be reset by ~1M blocks.

**Comment by PeaStew** [comment]
Courtesy of @etienne-napoleone:
1. don't docker-compose down as it will destroy the container
2. `docker-compose stop` (will only stop them)
3. `docker ps -a` find the id of the container
4. `docker cp $ID_OF_CONTAINER:/root/.tomo /var/lib/docker/volumes/$NAME_OF_CONTAINER_chaindata/_data/tomox`
6. `docker-compose pull`
7. `docker-compose up -d`

@thanhson1085

**Pull request merged**
